### ISSUE TITLE
Unable to interact with other contracts in constructor of contract with enhanced privacy

### ISSUE THREAD

**Issue by rodion-lim-partior** [ConsenSys/quorum#1563]
#### System information

Geth version: `Geth/32e486ea6b3f-istanbul/v1.10.2-stable-e5b930e8(quorum-v22.7.0)/linux-amd64/go1.16.15`
OS & Version: Linux

#### Expected behaviour
In the constructor for contracts deployed with enhanced privacy (e.g. party protection), we should be able to interact with other contracts that are deployed with the same enhanced privacy mode.

#### Actual behaviour
During the constructor call, the deployed contract is unable to find the bytecode of the second contract that it interacts with, even though the second contract is deployed with the same enhanced privacy mode, i.e. PP.

#### Steps to reproduce the behaviour
Attached a minimal example where a contract tries to interact with a second contract with same privacy enhancements mode in the constructor call.
[enhanced-privacy.tar.gz](https://github.com/ConsenSys/quorum/files/10073155/enhanced-privacy.tar.gz)

#### Backtrace

````
3_check_contract.js
===================

   Deploying 'PrivateConstructorCheckContract'
   -------------------------------------------
Unable to find contract code :: error  Error:  *** Deployment Failed ***

"PrivateConstructorCheckContract" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at module.exports (/home/user/workspace/enhanced-privacy/migrations/3_check_contract.js:15:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:73:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:231:1
````

**Comment by antonydenyer** [comment]
I think this has been fixed with https://github.com/ConsenSys/quorum/pull/1584 can you confirm? thanks

**Comment by matthew-alexander-partior** [comment]
I have tested the same reproduction code on go-quorum tag `v23.4.0` and confirmed that the issue still exists and wasn't fixed with #1584
